### ISSUE TITLE
Enable HTTP

### ISSUE THREAD

**Issue by sSiDs** [adamwoolhether/NetBox4CentOS8#3]
sorry) it is me again)
how enable http?

**Comment by sSiDs** [comment]
i have requested from admin ssl cert, but to raise up skills wanna know how to enable http for local intranet access

**Comment by adamwoolhether** [comment]
i'm not quite sure what you mean by 'enable http'. You mean Apache webserver? httpd? 

If apache is enabled you can navigate to the Netbox site from within the network.

**Comment by sSiDs** [comment]
no) i mean use **http** and **https** both
