### ISSUE TITLE
upgarde procedure to 2.10

### ISSUE THREAD

**Issue by sSiDs** [adamwoolhether/NetBox4CentOS8#4]
Good day!
Is the upgrade procedure is the same from netbox.docs or i can broke my netbox?
https://netbox.readthedocs.io/en/stable/installation/upgrading/
thnks!

**Comment by adamwoolhether** [comment]
Yes the upgrade procedure remains the same following the Netbox Official Docs.

I should create a playbook for the upgrade procedure as well.

**Comment by adamwoolhether** [comment]
I've added a simple .sh script to run the update process. Because the playbook uses git repo, it's a simple procedure and i think a playbook is unnecessary.
